"""Repository interfaces using typing.Protocol (port/adapter pattern)."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from core.entities import (
    Badge,
    BadgeCreate,
    DDAState,
    DDAStateCreate,
    Evaluation,
    EvaluationCreate,
    Scenario,
    ScenarioCreate,
    Session,
    SessionCreate,
    User,
    UserBadge,
    UserCreate,
    XPTransaction,
)


class UserRepository(Protocol):
    """Interface for user data access."""

    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[User]: ...
    async def create(self, data: UserCreate) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...
    async def count(self) -> int: ...
    async def get_leaderboard(self, limit: int = 10, skip: int = 0) -> list[User]: ...
    async def get_users_by_attributes(
        self, attributes: dict[str, str]
    ) -> list[User]: ...


class SessionRepository(Protocol):
    """Interface for session data access."""

    async def get_by_id(self, session_id: UUID) -> Session | None: ...
    async def list_by_user(
        self, user_id: UUID, skip: int = 0, limit: int = 100
    ) -> list[Session]: ...
    async def create(self, data: SessionCreate) -> Session: ...
    async def update(self, session: Session) -> Session: ...
    async def delete(self, session_id: UUID) -> None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[Session]: ...
    async def count_by_user(self, user_id: UUID) -> int: ...
    async def count_completed(self, user_id: UUID) -> int: ...


class ScenarioRepository(Protocol):
    """Interface for scenario data access."""

    async def get_by_id(self, scenario_id: UUID) -> Scenario | None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[Scenario]: ...
    async def create(self, data: ScenarioCreate) -> Scenario: ...
    async def update(self, scenario: Scenario) -> Scenario: ...
    async def delete(self, scenario_id: UUID) -> None: ...
    async def count(self) -> int: ...
    async def list_by_difficulty(self, difficulty: str) -> list[Scenario]: ...


class EvaluationRepository(Protocol):
    """Interface for evaluation data access."""

    async def get_by_id(self, evaluation_id: UUID) -> Evaluation | None: ...
    async def get_by_session(self, session_id: UUID) -> Evaluation | None: ...
    async def list_by_user(
        self, user_id: UUID, skip: int = 0, limit: int = 100
    ) -> list[Evaluation]: ...
    async def create(self, data: EvaluationCreate) -> Evaluation: ...
    async def update(self, evaluation: Evaluation) -> Evaluation: ...
    async def delete(self, evaluation_id: UUID) -> None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[Evaluation]: ...
    async def get_average_score(self, user_id: UUID) -> float: ...
    async def get_scores_by_user_ids(
        self,
        user_ids: list[UUID],
        scenario_ids: list[UUID] | None = None,
    ) -> dict[UUID, list[float]]: ...


class BadgeRepository(Protocol):
    """Interface for badge data access."""

    async def get_by_id(self, badge_id: UUID) -> Badge | None: ...
    async def list_all(self, skip: int = 0, limit: int = 100) -> list[Badge]: ...
    async def create(self, data: BadgeCreate) -> Badge: ...
    async def award_to_user(self, user_badge: UserBadge) -> UserBadge: ...
    async def get_user_badges(self, user_id: UUID) -> list[Badge]: ...
    async def has_user_badge(self, user_id: UUID, badge_id: UUID) -> bool: ...


class DDAStateRepository(Protocol):
    """Interface for DDA state data access."""

    async def get_by_session(self, session_id: UUID) -> DDAState | None: ...
    async def create(self, data: DDAStateCreate) -> DDAState: ...
    async def update(self, state: DDAState) -> DDAState: ...
    async def delete(self, session_id: UUID) -> None: ...
    async def list_stale(self, older_than: datetime) -> list[DDAState]: ...
    async def delete_stale(self, older_than: datetime) -> int: ...


class XPTransactionRepository(Protocol):
    """Interface for XP transaction data access."""

    async def create(self, txn: XPTransaction) -> XPTransaction: ...
    async def list_by_user(
        self, user_id: UUID, skip: int = 0, limit: int = 100
    ) -> list[XPTransaction]: ...
    async def count_by_user(self, user_id: UUID) -> int: ...
    async def get_total_xp(self, user_id: UUID) -> int: ...
